apiVersion: aim.sovereign.io/v1alpha1
kind: SovereignProject
metadata:
  name: sovereign-ai
spec:
  tenant: application-platform
  policyProfileRef: mvp-default
  applicationRepository:
    url: https://github.com/RampantBias/calculator-demo.git
    defaultRevision: 478daad19967dd08f13de44b6c7c8becb17d8c1e
    credentialRef:
      namespace: sovereign-orchestrator-system
      name: calculator-git
  validation:
    provider: argocd-kustomize
    infrastructureRepository: https://github.com/RampantBias/calculator-demo.git
    overlayPath: deploy/overlays/validation
    imageName: calculator
  testJob:
    image: registry.internal/sovereign/utility:dev
    command: ["/utility", "test"]
  buildJob:
    image: registry.internal/sovereign/utility:dev
    command: ["/utility", "build"]
    credentialRef:
      namespace: sovereign-orchestrator-system
      name: sovereign-ai-registry
