apiVersion: aim.sovereign.io/v1alpha1
kind: SovereignProject
metadata:
  name: sovereign-ai
spec:
  tenant: application-platform
  policyProfileRef: mvp-default
  applicationRepository:
    url: https://github.com/RampantBias/calculator-demo.git
    defaultRevision: 478daad19967dd08f13de44b6c7c8becb17d8c1e
    credentialRef:
      namespace: sovereign-orchestrator-system
      name: calculator-git
  validation:
    provider: argocd-kustomize
    infrastructureRepository: https://github.com/RampantBias/calculator-demo.git
    overlayPath: deploy/overlays/validation
    imageName: 192.168.1.19:30500/sovereign/calculator
  testJob:
    image: sovereign-test-runner:dev
    command: ["go", "test", "./..."]
  buildJob:
    image: sovereign-build-runner:dev
    command: ["/usr/bin/buildctl-daemonless.sh", "build"]
    args:
      - --frontend
      - dockerfile.v0
      - --local
      - context=/workspace
      - --local
      - dockerfile=/workspace
      - --output
      - type=image,name=192.168.1.19:30500/sovereign/calculator,push=true,registry.insecure=true
      - --metadata-file
      - /workspace/image-metadata.json
