apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sovereign-orchestrator-system

resources:
  - namespace.yaml
  - service-account.yaml
  - rbac.yaml
  - controller.yaml
  - controller-metrics-service.yaml
  - api.yaml
  - api-service.yaml
  - mcp.yaml
  - mcp-service.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: sovereign-ai
      app.kubernetes.io/managed-by: kustomize
