// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: orchestrator.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrchestratorService_CreateProject_FullMethodName        = "/api.v1.OrchestratorService/CreateProject"
	OrchestratorService_CleanWorkflow_FullMethodName        = "/api.v1.OrchestratorService/CleanWorkflow"
	OrchestratorService_CreateWorkflow_FullMethodName       = "/api.v1.OrchestratorService/CreateWorkflow"
	OrchestratorService_ListWorkflows_FullMethodName        = "/api.v1.OrchestratorService/ListWorkflows"
	OrchestratorService_GetWorkflowTimeline_FullMethodName  = "/api.v1.OrchestratorService/GetWorkflowTimeline"
	OrchestratorService_StoreContextSnapshot_FullMethodName = "/api.v1.OrchestratorService/StoreContextSnapshot"
	OrchestratorService_GetContextSnapshot_FullMethodName   = "/api.v1.OrchestratorService/GetContextSnapshot"
	OrchestratorService_GetWorkflowLineage_FullMethodName   = "/api.v1.OrchestratorService/GetWorkflowLineage"
	OrchestratorService_SubmitApproval_FullMethodName       = "/api.v1.OrchestratorService/SubmitApproval"
)

// OrchestratorServiceClient is the client API for OrchestratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Define the network service endpoints
type OrchestratorServiceClient interface {
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error)
	CleanWorkflow(ctx context.Context, in *CleanWorkflowRequest, opts ...grpc.CallOption) (*CleanWorkflowResponse, error)
	CreateWorkflow(ctx context.Context, in *CreateWorkflowRequest, opts ...grpc.CallOption) (*CreateWorkflowResponse, error)
	ListWorkflows(ctx context.Context, in *ListWorkflowsRequest, opts ...grpc.CallOption) (*ListWorkflowsResponse, error)
	GetWorkflowTimeline(ctx context.Context, in *GetWorkflowTimelineRequest, opts ...grpc.CallOption) (*GetWorkflowTimelineResponse, error)
	StoreContextSnapshot(ctx context.Context, in *StoreContextSnapshotRequest, opts ...grpc.CallOption) (*ContextSnapshotReceipt, error)
	GetContextSnapshot(ctx context.Context, in *GetContextSnapshotRequest, opts ...grpc.CallOption) (*GetContextSnapshotResponse, error)
	GetWorkflowLineage(ctx context.Context, in *GetWorkflowLineageRequest, opts ...grpc.CallOption) (*GetWorkflowLineageResponse, error)
	SubmitApproval(ctx context.Context, in *ApprovalSubmission, opts ...grpc.CallOption) (*ApprovalResponse, error)
}

type orchestratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorServiceClient(cc grpc.ClientConnInterface) OrchestratorServiceClient {
	return &orchestratorServiceClient{cc}
}

func (c *orchestratorServiceClient) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProjectResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_CreateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) CleanWorkflow(ctx context.Context, in *CleanWorkflowRequest, opts ...grpc.CallOption) (*CleanWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CleanWorkflowResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_CleanWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) CreateWorkflow(ctx context.Context, in *CreateWorkflowRequest, opts ...grpc.CallOption) (*CreateWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWorkflowResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_CreateWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) ListWorkflows(ctx context.Context, in *ListWorkflowsRequest, opts ...grpc.CallOption) (*ListWorkflowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkflowsResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_ListWorkflows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) GetWorkflowTimeline(ctx context.Context, in *GetWorkflowTimelineRequest, opts ...grpc.CallOption) (*GetWorkflowTimelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkflowTimelineResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_GetWorkflowTimeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) StoreContextSnapshot(ctx context.Context, in *StoreContextSnapshotRequest, opts ...grpc.CallOption) (*ContextSnapshotReceipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextSnapshotReceipt)
	err := c.cc.Invoke(ctx, OrchestratorService_StoreContextSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) GetContextSnapshot(ctx context.Context, in *GetContextSnapshotRequest, opts ...grpc.CallOption) (*GetContextSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContextSnapshotResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_GetContextSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) GetWorkflowLineage(ctx context.Context, in *GetWorkflowLineageRequest, opts ...grpc.CallOption) (*GetWorkflowLineageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkflowLineageResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_GetWorkflowLineage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) SubmitApproval(ctx context.Context, in *ApprovalSubmission, opts ...grpc.CallOption) (*ApprovalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApprovalResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_SubmitApproval_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorServiceServer is the server API for OrchestratorService service.
// All implementations must embed UnimplementedOrchestratorServiceServer
// for forward compatibility.
//
// Define the network service endpoints
type OrchestratorServiceServer interface {
	CreateProject(context.Context, *CreateProjectRequest) (*CreateProjectResponse, error)
	CleanWorkflow(context.Context, *CleanWorkflowRequest) (*CleanWorkflowResponse, error)
	CreateWorkflow(context.Context, *CreateWorkflowRequest) (*CreateWorkflowResponse, error)
	ListWorkflows(context.Context, *ListWorkflowsRequest) (*ListWorkflowsResponse, error)
	GetWorkflowTimeline(context.Context, *GetWorkflowTimelineRequest) (*GetWorkflowTimelineResponse, error)
	StoreContextSnapshot(context.Context, *StoreContextSnapshotRequest) (*ContextSnapshotReceipt, error)
	GetContextSnapshot(context.Context, *GetContextSnapshotRequest) (*GetContextSnapshotResponse, error)
	GetWorkflowLineage(context.Context, *GetWorkflowLineageRequest) (*GetWorkflowLineageResponse, error)
	SubmitApproval(context.Context, *ApprovalSubmission) (*ApprovalResponse, error)
	mustEmbedUnimplementedOrchestratorServiceServer()
}

// UnimplementedOrchestratorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestratorServiceServer struct{}

func (UnimplementedOrchestratorServiceServer) CreateProject(context.Context, *CreateProjectRequest) (*CreateProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProject not implemented")
}
func (UnimplementedOrchestratorServiceServer) CleanWorkflow(context.Context, *CleanWorkflowRequest) (*CleanWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CleanWorkflow not implemented")
}
func (UnimplementedOrchestratorServiceServer) CreateWorkflow(context.Context, *CreateWorkflowRequest) (*CreateWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWorkflow not implemented")
}
func (UnimplementedOrchestratorServiceServer) ListWorkflows(context.Context, *ListWorkflowsRequest) (*ListWorkflowsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkflows not implemented")
}
func (UnimplementedOrchestratorServiceServer) GetWorkflowTimeline(context.Context, *GetWorkflowTimelineRequest) (*GetWorkflowTimelineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkflowTimeline not implemented")
}
func (UnimplementedOrchestratorServiceServer) StoreContextSnapshot(context.Context, *StoreContextSnapshotRequest) (*ContextSnapshotReceipt, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreContextSnapshot not implemented")
}
func (UnimplementedOrchestratorServiceServer) GetContextSnapshot(context.Context, *GetContextSnapshotRequest) (*GetContextSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContextSnapshot not implemented")
}
func (UnimplementedOrchestratorServiceServer) GetWorkflowLineage(context.Context, *GetWorkflowLineageRequest) (*GetWorkflowLineageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkflowLineage not implemented")
}
func (UnimplementedOrchestratorServiceServer) SubmitApproval(context.Context, *ApprovalSubmission) (*ApprovalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitApproval not implemented")
}
func (UnimplementedOrchestratorServiceServer) mustEmbedUnimplementedOrchestratorServiceServer() {}
func (UnimplementedOrchestratorServiceServer) testEmbeddedByValue()                             {}

// UnsafeOrchestratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorServiceServer will
// result in compilation errors.
type UnsafeOrchestratorServiceServer interface {
	mustEmbedUnimplementedOrchestratorServiceServer()
}

func RegisterOrchestratorServiceServer(s grpc.ServiceRegistrar, srv OrchestratorServiceServer) {
	// If the following call panics, it indicates UnimplementedOrchestratorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrchestratorService_ServiceDesc, srv)
}

func _OrchestratorService_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_CreateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).CreateProject(ctx, req.(*CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_CleanWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).CleanWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_CleanWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).CleanWorkflow(ctx, req.(*CleanWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_CreateWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).CreateWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_CreateWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).CreateWorkflow(ctx, req.(*CreateWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_ListWorkflows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkflowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).ListWorkflows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_ListWorkflows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).ListWorkflows(ctx, req.(*ListWorkflowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_GetWorkflowTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkflowTimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).GetWorkflowTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_GetWorkflowTimeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).GetWorkflowTimeline(ctx, req.(*GetWorkflowTimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_StoreContextSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreContextSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).StoreContextSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_StoreContextSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).StoreContextSnapshot(ctx, req.(*StoreContextSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_GetContextSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContextSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).GetContextSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_GetContextSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).GetContextSnapshot(ctx, req.(*GetContextSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_GetWorkflowLineage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkflowLineageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).GetWorkflowLineage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_GetWorkflowLineage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).GetWorkflowLineage(ctx, req.(*GetWorkflowLineageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_SubmitApproval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApprovalSubmission)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).SubmitApproval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_SubmitApproval_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).SubmitApproval(ctx, req.(*ApprovalSubmission))
	}
	return interceptor(ctx, in, info, handler)
}

// OrchestratorService_ServiceDesc is the grpc.ServiceDesc for OrchestratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrchestratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.OrchestratorService",
	HandlerType: (*OrchestratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProject",
			Handler:    _OrchestratorService_CreateProject_Handler,
		},
		{
			MethodName: "CleanWorkflow",
			Handler:    _OrchestratorService_CleanWorkflow_Handler,
		},
		{
			MethodName: "CreateWorkflow",
			Handler:    _OrchestratorService_CreateWorkflow_Handler,
		},
		{
			MethodName: "ListWorkflows",
			Handler:    _OrchestratorService_ListWorkflows_Handler,
		},
		{
			MethodName: "GetWorkflowTimeline",
			Handler:    _OrchestratorService_GetWorkflowTimeline_Handler,
		},
		{
			MethodName: "StoreContextSnapshot",
			Handler:    _OrchestratorService_StoreContextSnapshot_Handler,
		},
		{
			MethodName: "GetContextSnapshot",
			Handler:    _OrchestratorService_GetContextSnapshot_Handler,
		},
		{
			MethodName: "GetWorkflowLineage",
			Handler:    _OrchestratorService_GetWorkflowLineage_Handler,
		},
		{
			MethodName: "SubmitApproval",
			Handler:    _OrchestratorService_SubmitApproval_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orchestrator.proto",
}
