// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/api/v1/orchestrator.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProjectRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ProjectName string                 `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	InfraRepo   string                 `protobuf:"bytes,2,opt,name=infra_repo,json=infraRepo,proto3" json:"infra_repo,omitempty"`
	AppRepo     string                 `protobuf:"bytes,3,opt,name=app_repo,json=appRepo,proto3" json:"app_repo,omitempty"`
	// The open extension point for enterprise variations
	StrategyType     string            `protobuf:"bytes,4,opt,name=strategy_type,json=strategyType,proto3" json:"strategy_type,omitempty"`                                                                                       // e.g., "single-repo", "enterprise-cluster"
	ExtendedMetadata map[string]string `protobuf:"bytes,5,rep,name=extended_metadata,json=extendedMetadata,proto3" json:"extended_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g., {"terraform_repo": "git://...", "shared_charts": "true"}
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_internal_api_v1_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_v1_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_v1_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProjectRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *CreateProjectRequest) GetInfraRepo() string {
	if x != nil {
		return x.InfraRepo
	}
	return ""
}

func (x *CreateProjectRequest) GetAppRepo() string {
	if x != nil {
		return x.AppRepo
	}
	return ""
}

func (x *CreateProjectRequest) GetStrategyType() string {
	if x != nil {
		return x.StrategyType
	}
	return ""
}

func (x *CreateProjectRequest) GetExtendedMetadata() map[string]string {
	if x != nil {
		return x.ExtendedMetadata
	}
	return nil
}

type CreateProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectResponse) Reset() {
	*x = CreateProjectResponse{}
	mi := &file_internal_api_v1_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectResponse) ProtoMessage() {}

func (x *CreateProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_v1_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectResponse.ProtoReflect.Descriptor instead.
func (*CreateProjectResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_v1_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProjectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateProjectResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CleanWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	ProjectName   string                 `protobuf:"bytes,2,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanWorkflowRequest) Reset() {
	*x = CleanWorkflowRequest{}
	mi := &file_internal_api_v1_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanWorkflowRequest) ProtoMessage() {}

func (x *CleanWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_v1_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanWorkflowRequest.ProtoReflect.Descriptor instead.
func (*CleanWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_v1_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *CleanWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *CleanWorkflowRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

type CleanWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanWorkflowResponse) Reset() {
	*x = CleanWorkflowResponse{}
	mi := &file_internal_api_v1_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanWorkflowResponse) ProtoMessage() {}

func (x *CleanWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_v1_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanWorkflowResponse.ProtoReflect.Descriptor instead.
func (*CleanWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_v1_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *CleanWorkflowResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CleanWorkflowResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// CreateWorkflow
type CreateWorkflowRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ProjectName          string                 `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	ManifestContent      string                 `protobuf:"bytes,2,opt,name=manifest_content,json=manifestContent,proto3" json:"manifest_content,omitempty"`
	ChangeRequestContent []byte                 `protobuf:"bytes,3,opt,name=change_request_content,json=changeRequestContent,proto3" json:"change_request_content,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateWorkflowRequest) Reset() {
	*x = CreateWorkflowRequest{}
	mi := &file_internal_api_v1_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkflowRequest) ProtoMessage() {}

func (x *CreateWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_v1_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkflowRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_v1_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *CreateWorkflowRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *CreateWorkflowRequest) GetManifestContent() string {
	if x != nil {
		return x.ManifestContent
	}
	return ""
}

func (x *CreateWorkflowRequest) GetChangeRequestContent() []byte {
	if x != nil {
		return x.ChangeRequestContent
	}
	return nil
}

type CreateWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkflowResponse) Reset() {
	*x = CreateWorkflowResponse{}
	mi := &file_internal_api_v1_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkflowResponse) ProtoMessage() {}

func (x *CreateWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_v1_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkflowResponse.ProtoReflect.Descriptor instead.
func (*CreateWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_v1_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *CreateWorkflowResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type ListWorkflowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectName   string                 `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsRequest) Reset() {
	*x = ListWorkflowsRequest{}
	mi := &file_internal_api_v1_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsRequest) ProtoMessage() {}

func (x *ListWorkflowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_v1_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkflowsRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_v1_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *ListWorkflowsRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

// The clean Data Transfer Object definition
type WorkflowStatusDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectName   string                 `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CurrentStep   string                 `protobuf:"bytes,4,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	Namespace     string                 `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowStatusDTO) Reset() {
	*x = WorkflowStatusDTO{}
	mi := &file_internal_api_v1_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowStatusDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowStatusDTO) ProtoMessage() {}

func (x *WorkflowStatusDTO) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_v1_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowStatusDTO.ProtoReflect.Descriptor instead.
func (*WorkflowStatusDTO) Descriptor() ([]byte, []int) {
	return file_internal_api_v1_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *WorkflowStatusDTO) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *WorkflowStatusDTO) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WorkflowStatusDTO) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkflowStatusDTO) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

func (x *WorkflowStatusDTO) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type ListWorkflowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflows     []*WorkflowStatusDTO   `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"` // 'repeated' represents an array/slice in Go
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsResponse) Reset() {
	*x = ListWorkflowsResponse{}
	mi := &file_internal_api_v1_orchestrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsResponse) ProtoMessage() {}

func (x *ListWorkflowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_v1_orchestrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkflowsResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_v1_orchestrator_proto_rawDescGZIP(), []int{8}
}

func (x *ListWorkflowsResponse) GetWorkflows() []*WorkflowStatusDTO {
	if x != nil {
		return x.Workflows
	}
	return nil
}

type GetWorkflowTimelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowTimelineRequest) Reset() {
	*x = GetWorkflowTimelineRequest{}
	mi := &file_internal_api_v1_orchestrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowTimelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowTimelineRequest) ProtoMessage() {}

func (x *GetWorkflowTimelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_v1_orchestrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowTimelineRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowTimelineRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_v1_orchestrator_proto_rawDescGZIP(), []int{9}
}

func (x *GetWorkflowTimelineRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type AuditActorDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditActorDTO) Reset() {
	*x = AuditActorDTO{}
	mi := &file_internal_api_v1_orchestrator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditActorDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditActorDTO) ProtoMessage() {}

func (x *AuditActorDTO) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_v1_orchestrator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditActorDTO.ProtoReflect.Descriptor instead.
func (*AuditActorDTO) Descriptor() ([]byte, []int) {
	return file_internal_api_v1_orchestrator_proto_rawDescGZIP(), []int{10}
}

func (x *AuditActorDTO) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AuditActorDTO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AuditSubjectDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	WorkflowName  string                 `protobuf:"bytes,3,opt,name=workflowName,proto3" json:"workflow,omitempty"`
	Step          string                 `protobuf:"bytes,4,opt,name=step,proto3" json:"step,omitempty"`
	Attempt       int32                  `protobuf:"varint,5,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditSubjectDTO) Reset() {
	*x = AuditSubjectDTO{}
	mi := &file_internal_api_v1_orchestrator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditSubjectDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditSubjectDTO) ProtoMessage() {}

func (x *AuditSubjectDTO) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_v1_orchestrator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditSubjectDTO.ProtoReflect.Descriptor instead.
func (*AuditSubjectDTO) Descriptor() ([]byte, []int) {
	return file_internal_api_v1_orchestrator_proto_rawDescGZIP(), []int{11}
}

func (x *AuditSubjectDTO) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *AuditSubjectDTO) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AuditSubjectDTO) GetWorkflow() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *AuditSubjectDTO) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *AuditSubjectDTO) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type AuditEventDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	SchemaVersion string                 `protobuf:"bytes,3,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	OccurredAt    string                 `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	RecordedAt    string                 `protobuf:"bytes,5,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`
	Actor         *AuditActorDTO         `protobuf:"bytes,6,opt,name=actor,proto3" json:"actor,omitempty"`
	Subject       *AuditSubjectDTO       `protobuf:"bytes,7,opt,name=subject,proto3" json:"subject,omitempty"`
	Action        string                 `protobuf:"bytes,8,opt,name=action,proto3" json:"action,omitempty"`
	Target        string                 `protobuf:"bytes,9,opt,name=target,proto3" json:"target,omitempty"`
	Outcome       string                 `protobuf:"bytes,10,opt,name=outcome,proto3" json:"outcome,omitempty"`
	Reason        string                 `protobuf:"bytes,11,opt,name=reason,proto3" json:"reason,omitempty"`
	CorrelationId string                 `protobuf:"bytes,12,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	CausationId   string                 `protobuf:"bytes,13,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	DecisionId    string                 `protobuf:"bytes,14,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	References    map[string]string      `protobuf:"bytes,15,rep,name=references,proto3" json:"references,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DataJson      string                 `protobuf:"bytes,16,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEventDTO) Reset() {
	*x = AuditEventDTO{}
	mi := &file_internal_api_v1_orchestrator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEventDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEventDTO) ProtoMessage() {}

func (x *AuditEventDTO) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_v1_orchestrator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEventDTO.ProtoReflect.Descriptor instead.
func (*AuditEventDTO) Descriptor() ([]byte, []int) {
	return file_internal_api_v1_orchestrator_proto_rawDescGZIP(), []int{12}
}

func (x *AuditEventDTO) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditEventDTO) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AuditEventDTO) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *AuditEventDTO) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

func (x *AuditEventDTO) GetRecordedAt() string {
	if x != nil {
		return x.RecordedAt
	}
	return ""
}

func (x *AuditEventDTO) GetActor() *AuditActorDTO {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *AuditEventDTO) GetSubject() *AuditSubjectDTO {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *AuditEventDTO) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditEventDTO) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *AuditEventDTO) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *AuditEventDTO) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AuditEventDTO) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AuditEventDTO) GetCausationId() string {
	if x != nil {
		return x.CausationId
	}
	return ""
}

func (x *AuditEventDTO) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *AuditEventDTO) GetReferences() map[string]string {
	if x != nil {
		return x.References
	}
	return nil
}

func (x *AuditEventDTO) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

type GetWorkflowTimelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*AuditEventDTO       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowTimelineResponse) Reset() {
	*x = GetWorkflowTimelineResponse{}
	mi := &file_internal_api_v1_orchestrator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowTimelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowTimelineResponse) ProtoMessage() {}

func (x *GetWorkflowTimelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_v1_orchestrator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowTimelineResponse.ProtoReflect.Descriptor instead.
func (*GetWorkflowTimelineResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_v1_orchestrator_proto_rawDescGZIP(), []int{13}
}

func (x *GetWorkflowTimelineResponse) GetEvents() []*AuditEventDTO {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_internal_api_v1_orchestrator_proto protoreflect.FileDescriptor

const file_internal_api_v1_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\"internal/api/v1/orchestrator.proto\x12\x06api.v1\"\xbe\x02\n" +
	"\x14CreateProjectRequest\x12!\n" +
	"\fproject_name\x18\x01 \x01(\tR\vprojectName\x12\x1d\n" +
	"\n" +
	"infra_repo\x18\x02 \x01(\tR\tinfraRepo\x12\x19\n" +
	"\bapp_repo\x18\x03 \x01(\tR\aappRepo\x12#\n" +
	"\rstrategy_type\x18\x04 \x01(\tR\fstrategyType\x12_\n" +
	"\x11extended_metadata\x18\x05 \x03(\v22.api.v1.CreateProjectRequest.ExtendedMetadataEntryR\x10extendedMetadata\x1aC\n" +
	"\x15ExtendedMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"K\n" +
	"\x15CreateProjectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"Z\n" +
	"\x14CleanWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12!\n" +
	"\fproject_name\x18\x02 \x01(\tR\vprojectName\"K\n" +
	"\x15CleanWorkflowResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9b\x01\n" +
	"\x15CreateWorkflowRequest\x12!\n" +
	"\fproject_name\x18\x01 \x01(\tR\vprojectName\x12)\n" +
	"\x10manifest_content\x18\x02 \x01(\tR\x0fmanifestContent\x124\n" +
	"\x16change_request_content\x18\x03 \x01(\fR\x14changeRequestContent\"9\n" +
	"\x16CreateWorkflowResponse\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"9\n" +
	"\x14ListWorkflowsRequest\x12!\n" +
	"\fproject_name\x18\x01 \x01(\tR\vprojectName\"\xb0\x01\n" +
	"\x11WorkflowStatusDTO\x12!\n" +
	"\fproject_name\x18\x01 \x01(\tR\vprojectName\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\fcurrent_step\x18\x04 \x01(\tR\vcurrentStep\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\"P\n" +
	"\x15ListWorkflowsResponse\x127\n" +
	"\tworkflows\x18\x01 \x03(\v2\x19.api.v1.WorkflowStatusDTOR\tworkflows\"=\n" +
	"\x1aGetWorkflowTimelineRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"3\n" +
	"\rAuditActorDTO\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\x93\x01\n" +
	"\x0fAuditSubjectDTO\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1a\n" +
	"\bworkflow\x18\x03 \x01(\tR\bworkflow\x12\x12\n" +
	"\x04step\x18\x04 \x01(\tR\x04step\x12\x18\n" +
	"\aattempt\x18\x05 \x01(\x05R\aattempt\"\xec\x04\n" +
	"\rAuditEventDTO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12%\n" +
	"\x0eschema_version\x18\x03 \x01(\tR\rschemaVersion\x12\x1f\n" +
	"\voccurred_at\x18\x04 \x01(\tR\n" +
	"occurredAt\x12\x1f\n" +
	"\vrecorded_at\x18\x05 \x01(\tR\n" +
	"recordedAt\x12+\n" +
	"\x05actor\x18\x06 \x01(\v2\x15.api.v1.AuditActorDTOR\x05actor\x121\n" +
	"\asubject\x18\a \x01(\v2\x17.api.v1.AuditSubjectDTOR\asubject\x12\x16\n" +
	"\x06action\x18\b \x01(\tR\x06action\x12\x16\n" +
	"\x06target\x18\t \x01(\tR\x06target\x12\x18\n" +
	"\aoutcome\x18\n" +
	" \x01(\tR\aoutcome\x12\x16\n" +
	"\x06reason\x18\v \x01(\tR\x06reason\x12%\n" +
	"\x0ecorrelation_id\x18\f \x01(\tR\rcorrelationId\x12!\n" +
	"\fcausation_id\x18\r \x01(\tR\vcausationId\x12\x1f\n" +
	"\vdecision_id\x18\x0e \x01(\tR\n" +
	"decisionId\x12E\n" +
	"\n" +
	"references\x18\x0f \x03(\v2%.api.v1.AuditEventDTO.ReferencesEntryR\n" +
	"references\x12\x1b\n" +
	"\tdata_json\x18\x10 \x01(\tR\bdataJson\x1a=\n" +
	"\x0fReferencesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"L\n" +
	"\x1bGetWorkflowTimelineResponse\x12-\n" +
	"\x06events\x18\x01 \x03(\v2\x15.api.v1.AuditEventDTOR\x06events2\xb0\x03\n" +
	"\x13OrchestratorService\x12L\n" +
	"\rCreateProject\x12\x1c.api.v1.CreateProjectRequest\x1a\x1d.api.v1.CreateProjectResponse\x12L\n" +
	"\rCleanWorkflow\x12\x1c.api.v1.CleanWorkflowRequest\x1a\x1d.api.v1.CleanWorkflowResponse\x12O\n" +
	"\x0eCreateWorkflow\x12\x1d.api.v1.CreateWorkflowRequest\x1a\x1e.api.v1.CreateWorkflowResponse\x12L\n" +
	"\rListWorkflows\x12\x1c.api.v1.ListWorkflowsRequest\x1a\x1d.api.v1.ListWorkflowsResponse\x12^\n" +
	"\x13GetWorkflowTimeline\x12\".api.v1.GetWorkflowTimelineRequest\x1a#.api.v1.GetWorkflowTimelineResponseB\vZ\tapi/v1/pbb\x06proto3"

var (
	file_internal_api_v1_orchestrator_proto_rawDescOnce sync.Once
	file_internal_api_v1_orchestrator_proto_rawDescData []byte
)

func file_internal_api_v1_orchestrator_proto_rawDescGZIP() []byte {
	file_internal_api_v1_orchestrator_proto_rawDescOnce.Do(func() {
		file_internal_api_v1_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_v1_orchestrator_proto_rawDesc), len(file_internal_api_v1_orchestrator_proto_rawDesc)))
	})
	return file_internal_api_v1_orchestrator_proto_rawDescData
}

var file_internal_api_v1_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_internal_api_v1_orchestrator_proto_goTypes = []any{
	(*CreateProjectRequest)(nil),        // 0: api.v1.CreateProjectRequest
	(*CreateProjectResponse)(nil),       // 1: api.v1.CreateProjectResponse
	(*CleanWorkflowRequest)(nil),        // 2: api.v1.CleanWorkflowRequest
	(*CleanWorkflowResponse)(nil),       // 3: api.v1.CleanWorkflowResponse
	(*CreateWorkflowRequest)(nil),       // 4: api.v1.CreateWorkflowRequest
	(*CreateWorkflowResponse)(nil),      // 5: api.v1.CreateWorkflowResponse
	(*ListWorkflowsRequest)(nil),        // 6: api.v1.ListWorkflowsRequest
	(*WorkflowStatusDTO)(nil),           // 7: api.v1.WorkflowStatusDTO
	(*ListWorkflowsResponse)(nil),       // 8: api.v1.ListWorkflowsResponse
	(*GetWorkflowTimelineRequest)(nil),  // 9: api.v1.GetWorkflowTimelineRequest
	(*AuditActorDTO)(nil),               // 10: api.v1.AuditActorDTO
	(*AuditSubjectDTO)(nil),             // 11: api.v1.AuditSubjectDTO
	(*AuditEventDTO)(nil),               // 12: api.v1.AuditEventDTO
	(*GetWorkflowTimelineResponse)(nil), // 13: api.v1.GetWorkflowTimelineResponse
	nil,                                 // 14: api.v1.CreateProjectRequest.ExtendedMetadataEntry
	nil,                                 // 15: api.v1.AuditEventDTO.ReferencesEntry
}
var file_internal_api_v1_orchestrator_proto_depIdxs = []int32{
	14, // 0: api.v1.CreateProjectRequest.extended_metadata:type_name -> api.v1.CreateProjectRequest.ExtendedMetadataEntry
	7,  // 1: api.v1.ListWorkflowsResponse.workflows:type_name -> api.v1.WorkflowStatusDTO
	10, // 2: api.v1.AuditEventDTO.actor:type_name -> api.v1.AuditActorDTO
	11, // 3: api.v1.AuditEventDTO.subject:type_name -> api.v1.AuditSubjectDTO
	15, // 4: api.v1.AuditEventDTO.references:type_name -> api.v1.AuditEventDTO.ReferencesEntry
	12, // 5: api.v1.GetWorkflowTimelineResponse.events:type_name -> api.v1.AuditEventDTO
	0,  // 6: api.v1.OrchestratorService.CreateProject:input_type -> api.v1.CreateProjectRequest
	2,  // 7: api.v1.OrchestratorService.CleanWorkflow:input_type -> api.v1.CleanWorkflowRequest
	4,  // 8: api.v1.OrchestratorService.CreateWorkflow:input_type -> api.v1.CreateWorkflowRequest
	6,  // 9: api.v1.OrchestratorService.ListWorkflows:input_type -> api.v1.ListWorkflowsRequest
	9,  // 10: api.v1.OrchestratorService.GetWorkflowTimeline:input_type -> api.v1.GetWorkflowTimelineRequest
	1,  // 11: api.v1.OrchestratorService.CreateProject:output_type -> api.v1.CreateProjectResponse
	3,  // 12: api.v1.OrchestratorService.CleanWorkflow:output_type -> api.v1.CleanWorkflowResponse
	5,  // 13: api.v1.OrchestratorService.CreateWorkflow:output_type -> api.v1.CreateWorkflowResponse
	8,  // 14: api.v1.OrchestratorService.ListWorkflows:output_type -> api.v1.ListWorkflowsResponse
	13, // 15: api.v1.OrchestratorService.GetWorkflowTimeline:output_type -> api.v1.GetWorkflowTimelineResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_internal_api_v1_orchestrator_proto_init() }
func file_internal_api_v1_orchestrator_proto_init() {
	if File_internal_api_v1_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_v1_orchestrator_proto_rawDesc), len(file_internal_api_v1_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_v1_orchestrator_proto_goTypes,
		DependencyIndexes: file_internal_api_v1_orchestrator_proto_depIdxs,
		MessageInfos:      file_internal_api_v1_orchestrator_proto_msgTypes,
	}.Build()
	File_internal_api_v1_orchestrator_proto = out.File
	file_internal_api_v1_orchestrator_proto_goTypes = nil
	file_internal_api_v1_orchestrator_proto_depIdxs = nil
}
