apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    app.kubernetes.io/part-of: sovereign-ai-demo
    app.kubernetes.io/component: argocd
    app.kubernetes.io/managed-by: sovereign-ai-demo
