apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sovereign-validation-provider
  namespace: argocd
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["applications"]
    verbs: ["create", "get", "patch", "delete"]
  - apiGroups: ["argoproj.io"]
    resources: ["appprojects"]
    verbs: ["create", "get", "patch"]