apiVersion: v1
kind: Service
metadata:
  name: registry-headless
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: registry
  ports:
    - name: registry
      port: 5000
      targetPort: registry
---
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: registry
  ports:
    - name: registry
      port: 5000
      targetPort: registry
      nodePort: 30500
