apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - aim.sovereign.io_agentruns.yaml
  - aim.sovereign.io_approvaldecisions.yaml
  - aim.sovereign.io_approvalrequests.yaml
  - aim.sovereign.io_artifacts.yaml
  - aim.sovereign.io_humansessions.yaml
  - aim.sovereign.io_inferenceendpoints.yaml
  - aim.sovereign.io_inferenceleases.yaml
  - aim.sovereign.io_policyprofiles.yaml
  - aim.sovereign.io_sovereignprojects.yaml
  - aim.sovereign.io_sovereignworkflows.yaml
  - aim.sovereign.io_stepattempts.yaml
  - aim.sovereign.io_utilityoperations.yaml
  - aim.sovereign.io_validationruns.yaml
