apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sovereign-audit

resources:
  - namespace.yaml
  - service.yaml
  - statefulset.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: sovereign-ai-demo
      app.kubernetes.io/component: postgresql
